### ISSUE TITLE
`user` related thing should be an DTO instead of plain attribute

### ISSUE THREAD

**Issue by YJack0000** [YJack0000/document-center-be#29]
![Screenshot 2024-05-31 at 9 38 05 PM](https://github.com/YJack0000/document-center-be/assets/49984479/57b28641-a5d6-4822-8452-4e0e547a80be)

There are more detailed explain:

`owner` should be
```
"owner": {
    "id": "aaaa",
     "name": "aaaa"
}
```

`user` also should be
```
"user": {
    "id": "aaaa",
     "name": "aaaa"
}
```

**Comment by grace0950** [comment]
It was already fixed before.
