### ISSUE TITLE
User Name Undefined

### ISSUE THREAD

**Issue by yui0303** [YJack0000/document-center-be#34]
It seems the parser has some problem. Need to handle the First name or the Last name is/are empty.

Btw, should we handle the order of the chinese name?

![image](https://github.com/YJack0000/document-center-be/assets/111721739/d74bc757-feb8-436c-83b1-8d52399f1b4b)

**Comment by grace0950** [comment]
I can't handle the ordering of the Chinese name; that is managed by Google OAuth.
